travis:
  secure:
    BINSTAR_TOKEN: VjvtxtPrC1Nz8VX1y2foKpb2dlmRu5fXTKqRl3cnvfzXMrGAQBQNyAcvTu8mdq/ypg7PWsiVb0dJ8mHji5cWtlPUeRapz9nFuYPbR05HayzAL0PRoDov78Zs3g1GKPjuUTYivJouJYVs4PukYH6BwkpAurCDMvOGc8qI+pUTX9eUjm70Yil5ZlgEUxe6TOMRfNUqrUSV7IxzpnZ8lgscDsitoGkRftA8NIO7Z/z3fHkfJtnjvW3tIGD/En4aLH6ISEP5sBiSClA20hmJ85cSjc4D2Dm0cV5dyq9vsmQCYQxwa9yrWZWaKMPjq5fZKHJBXNOtnbiV0+IHHNSdKj3xFlIRISPXrt3n15ujtTY2q23HhCplW4uKemTslffS6A5x/3ZWC4xcQhq5UYeIEnnjXvK2sTaAtW8/eQXXhO3I8lBfBRixVJZjYhulAmAOFaGJbNwq0eHqJBwG2Mak+oeT2dZkcJiUQNbiT+lmlsWU3/GlZ9q7+c7odPxNcTSwSe1AbGJe0Ja29CG6QRby8/wp2CX21SnDu3iRQ8fityv8DdQuhUrg48g7Vy07PQ4uTo3kdY1m93yeJXBByxxo0x4JaRx9iiB8ltjtp/SGY27YzYhEelLS593k4HYUtfSJEns96cMnQWqOTZKDAd7JoC6FU8Fyen443gPiWmi4OFgXE+s=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
